name:                eve-codes
version:             0.1.0.0
github:              "tshearman/eve-codes"
license:             BSD3
author:              "Toby Shearman"
maintainer:          "toby@estimatingnature.com"
copyright:           "2020 Toby Shearman"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README.

dependencies:
- QuickCheck
- aeson
- async
- base
- bytestring
- case-insensitive
- containers
- hspec
- http-conduit
- http-types
- lens
- lens-aeson
- nats
- optparse-applicative
- parallel
- postgresql-simple
- text
- time
- wreq

library:
  source-dirs: src

executables:
  eve-universe:
    main: Universe.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -main-is Universe
    dependencies:
    - eve-codes

  eve-orders:
    main: Orders.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -main-is Orders
    dependencies:
    - eve-codes

tests:
  eve-codes-unit-tests:
    main:                Spec.hs
    source-dirs:         test/unit
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
    - eve-codes
